const query = "SELECT AY_KODU, FISNO, SIRA, HES_KOD, TARIH,"+
" CASE WHEN BA = 1 THEN 'BORÇ' WHEN BA = 2 THEN 'ALACAK' END AS [B/A],"+
" CASE WHEN BA = 1 THEN TUTAR WHEN BA = 2 (TUTAR*-1) END AS [TUTAR],"+
" REF_KOD, PROJE_KODU, LEFT(ENTEGREFKEY,3) AS [BELGE_TİPİ]," +
" SUBSTRING(ENTEGREFKEY,4,15) AS [BELGE_NO],"+
" RIGHT(ENTEGREFKEY,11) AS [KARSI_HESAP],"+
" KAYITYAPANKUL, KAYITTARIHI, DUZELTMEYAPANKUL, DUZELTMETARIHI, ENTEGREFKEY, ACIKLAMA"+
" FROM TBLMUHFIS"+

" WHERE TARIH BETWEEN '2024-01-01' AND '2024-12-31'"+
" AND HES_KOD LIKE '7%'"+
" AND LEFT(HES_KOD,3) <> RIGHT(REF_KOD,3)";



module.exports = query;